<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aurora.Core\Aurora.Core.csproj" />
    <ProjectReference Include="..\Aurora.Protocol\Aurora.Protocol.csproj" />
    <ProjectReference Include="..\Aurora.World\Aurora.World.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
