<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aurora.Core\Aurora.Core.csproj" />
    <EmbeddedResource Include="Data\blocks.bin" />
    <EmbeddedResource Include="Data\items.bin" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
